# ndarrray的基本操作

In [ ]:
from mxnet import nd

In [ ]:
x=nd.arange(12)
x

In [ ]:
x.shape

In [ ]:
x.size

In [ ]:
x.reshape(3,4)

In [ ]:
X=nd.zeros((2,3,4))
X

In [ ]:
X=nd.ones((3,4))
X

In [ ]:
Y=nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y

In [ ]:
z=X+y
z

In [ ]:
u=nd.array([[1,2,3],[3,2,1]])
u+z
##广播机制只能使用于矩阵

In [ ]:
#广播机制
x=nd.arange(1,4).reshape(1,3)
y=nd.arange(3).reshape(3,1)
x+y

In [ ]:
X+Y

In [ ]:
X/Y

In [ ]:
X*Y

In [ ]:
nd.dot(X,Y.T)

In [ ]:
nd.exp(X)

In [ ]:
X.exp()

In [ ]:
X==Y

In [ ]:
nd.concat(X,Y)

In [ ]:
nd.concat(X,Y,dim=0)

In [ ]:
X.sum()

In [ ]:
#X的L2范数
X.norm().asscalar()

In [ ]:
X[1:3]

In [ ]:
X[1:3,1:2]

In [ ]:
X[1,2]=9
X

In [ ]:
Z=X.zeros_like()
Z

In [ ]:
#u每次被赋值时都会产生X+Y的临时内存
u=X+Y
u

In [ ]:
#为了避免这个临时内存的开销，可以使用运算符全命名函数中的out函数
before=X+Y
Z=before
nd.elemwise_add(X,Y,out=Z)
id(before)==id(Z)

In [ ]:
#如果某个参数X的值不再使用，可以使用
X+=Y

In [ ]:
X.asnumpy()

# 梯度求解

In [1]:
from mxnet import autograd, nd

In [ ]:
#为了求梯度，需要用attach_grad获取储存梯度的内存
x=nd.arange(4).reshape(4,1)
x.attach_grad()

In [ ]:
##mxnet为减少内存开销，默认条件下不会记录求梯度过程，我们需要用record函数来记录与梯度相关的计算
with autograd.record():
    y=2*nd.dot(x.T,x)
    y.backward()
y/x

In [ ]:
assert ( x.grad -4*x).norm().asscalar()==0

In [ ]:
##在调用record函数后，默认情况下会将运行模式转为训练模式
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

In [22]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

a=nd.random.normal(shape=(20,3))
print(a)
a.attach_grad()
with autograd.record():
    c=f(a)
    print(c)
c.backward()
c/a


[[-2.0320427   0.12535118  1.1308912 ]
 [ 0.7975923   0.3951814   0.28870544]
 [ 0.9324615  -0.23988613 -0.56608427]
 [-0.39505458 -0.4548878   0.06443289]
 [ 0.5373315   0.5443839  -0.7556804 ]
 [-0.9151002   0.13664998  0.6581289 ]
 [-0.4829211  -0.52573365 -0.56757694]
 [ 0.5815633   0.28752208 -0.04466231]
 [ 1.2711253  -0.22282615 -0.13130406]
 [-2.3504982  -1.0225859  -3.063631  ]
 [-0.16971476 -1.0315224  -1.7215557 ]
 [-0.51747125 -0.14015885  0.36172876]
 [-0.39974266  1.5681199   1.5267444 ]
 [-0.06284162 -1.0716764   1.1127799 ]
 [-0.63718027  1.1728598   1.1777918 ]
 [ 0.39020136 -0.47798824 -0.6830585 ]
 [-0.98043364 -0.45766     1.500102  ]
 [-0.98644793  0.19554725  1.245432  ]
 [ 0.08104635 -0.6698103   0.05762542]
 [-0.10484769  0.11729875 -1.1180092 ]]
<NDArray 20x3 @cpu(0)>

[[-52020.293    3208.99    28950.814 ]
 [ 20418.363   10116.644    7390.8594]
 [ 23871.014   -6141.085  -14491.757 ]
 [-10113.397  -11645.128    1649.4819]
 [ 13755.687   13936.228  -19345.418 ]


[[25600.    25600.    25600.   ]
 [25600.002 25600.    25600.   ]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25599.998]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25600.002]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25600.   ]
 [25599.998 25600.    25600.002]
 [25600.    25600.    25600.   ]
 [25600.    25599.998 25600.   ]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25600.   ]
 [25600.002 25600.    25599.998]
 [25600.    25600.    25600.   ]
 [25600.    25600.    25600.   ]
 [25600.    25600.002 25600.   ]
 [25600.    25600.    25600.   ]]
<NDArray 20x3 @cpu(0)>

In [21]:
(-15146.237 )/(-0.5916499)

25599.999256316954

In [ ]:
print(a.grad,c/a)

In [ ]:
a.grad==c/a
##说明用backward函数求导是对的

In [103]:
x=nd.random.normal(shape=(2,2))
y=nd.random.normal(shape=(2,1))
print(x)
def g(a):
    return nd.dot(x,y)
g(x)


[[0.00402608 0.0900996 ]
 [0.3694024  0.233415  ]]
<NDArray 2x2 @cpu(0)>



[[-0.08212954]
 [-0.5370728 ]]
<NDArray 2x1 @cpu(0)>

In [104]:
x.attach_grad()
with autograd.record():
    c=g(x)
    print(x,c)
c.backward()
x.grad


[[0.00402608 0.0900996 ]
 [0.3694024  0.233415  ]]
<NDArray 2x2 @cpu(0)> 
[[-0.08212954]
 [-0.5370728 ]]
<NDArray 2x1 @cpu(0)>



[[-0.903427   -0.87117225]
 [-0.903427   -0.87117225]]
<NDArray 2x2 @cpu(0)>

In [99]:
l=0
m=0
for i in x:
    l+=i[0]
print(l)
for i in c:
    for j in i:
        m+=j
print(m)
print(m/l)


[0.36351895]
<NDArray 1 @cpu(0)>

[6.6627426]
<NDArray 1 @cpu(0)>

[18.32846]
<NDArray 1 @cpu(0)>


In [43]:
from mxnet import autograd
dir(autograd.backward)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']